In [88]:
import pandas as pd

df_madrid = pd.read_csv('Datos.csv')
print(df_madrid.head())

  provincia           zona                                             titulo  \
0    madrid  ciudad-lineal   Piso en calle de San Marcelo, 22, Ventas, Madrid
1    madrid    carabanchel  Piso en calle Cabo Nicolás Mur, San Isidro, Ma...
2    madrid         centro  Piso en calle de Rodas, Lavapiés-Embajadores, ...
3    madrid          usera  Piso en calle de Ferroviarios, Almendrales, Ma...
4    madrid         tetuan                    Dúplex en Bellas Vistas, Madrid

   PrecioActual  PrecioAnterior  metros  habitaciones ascensor localizacion  \
0        355000               0      69           2.0        S     EXTERIOR
1        149000          159000      91           3.0        N     EXTERIOR
2        195000               0      36           1.0        S          NaN
3        195000               0      58           1.0        S     INTERIOR
4        715000          750000     140           3.0        S     EXTERIOR

  planta  baños                                               tags  \
0     5ª      1  VIVIENDA,LUMINOSO,VISTAS,REFORMADA,PORTERO,EXT...
1     1ª      0            PISO,EXCLUSIVA,INMOBILIARIA,OPORTUNIDAD
2     2ª      0                                  EXCLUSIVA,ESTUDIO
3   BAJO      0                           VIVIENDA,HOGAR,FUNCIONAL
4     2ª      0                          TERRAZA,EXCLUSIVA,MODERNO

                                         descripcion  \
0  Particular Vende vivienda totalmente reformada...
1  Inmobiliarias Encuentro vende en exclusiva la ...
2  ESTUDIO EN PLENO CENTRO DE MADRIDSarago Servic...
3  Esta acogedora vivienda, ubicada en una planta...
4  Maravilloso ATICO de reciente construcción, co...

                                          Enlace
0  https://www.idealista.com/inmueble/106956987/
1  https://www.idealista.com/inmueble/106906044/
2  https://www.idealista.com/inmueble/107306175/
3  https://www.idealista.com/inmueble/106325171/
4  https://www.idealista.com/inmueble/106627265/

In [89]:
df_madrid.shape

(11826, 14)

In [90]:
df_madrid.head()

,provincia,zona,titulo,PrecioActual,PrecioAnterior,metros,habitaciones,ascensor,localizacion,planta,baños,tags,descripcion,Enlace
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,0,69,2.0,S,EXTERIOR,5ª,1,"VIVIENDA,LUMINOSO,VISTAS,REFORMADA,PORTERO,EXT...",Particular Vende vivienda totalmente reformada...,https://www.idealista.com/inmueble/106956987/
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,159000,91,3.0,N,EXTERIOR,1ª,0,"PISO,EXCLUSIVA,INMOBILIARIA,OPORTUNIDAD",Inmobiliarias Encuentro vende en exclusiva la ...,https://www.idealista.com/inmueble/106906044/
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,0,36,1.0,S,NaN,2ª,0,"EXCLUSIVA,ESTUDIO",ESTUDIO EN PLENO CENTRO DE MADRIDSarago Servic...,https://www.idealista.com/inmueble/107306175/
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,0,58,1.0,S,INTERIOR,BAJO,0,"VIVIENDA,HOGAR,FUNCIONAL","Esta acogedora vivienda, ubicada en una planta...",https://www.idealista.com/inmueble/106325171/
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,750000,140,3.0,S,EXTERIOR,2ª,0,"TERRAZA,EXCLUSIVA,MODERNO","Maravilloso ATICO de reciente construcción, co...",https://www.idealista.com/inmueble/106627265/

In [91]:
df_madrid.columns = df_madrid.columns.str.lower()

In [92]:
df_madrid = df_madrid.rename(columns ={'precioactual': 'precio_actual'})

In [93]:
columns_to_drop = { 
    'precioanterior',
    'localizacion',
    'tags',
    'descripcion',
    'enlace',
}
df_madrid = df_madrid.drop(columns=columns_to_drop)

In [94]:
df_madrid.head()

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0

In [95]:
df_madrid.isnull().sum()

provincia           0
zona                0
titulo              0
precio_actual       0
metros              0
habitaciones      366
ascensor          793
planta           1225
baños               0
dtype: int64

In [96]:
## PARA UNIFICAR VALORES NULOS DE LA SERIE 'PLANTA' DECIIDIMOS RELLENARLOS CON LA POSICIÓN DE ARRIBA. 
df_madrid['planta'].value_counts(dropna = False)

planta
1ª             2108
2ª             1779
3ª             1570
BAJO           1509
4ª             1266
NaN            1225
5ª              816
6ª              574
7ª              289
ENTREPLANTA     163
SÓTANO          128
8ª              124
9ª              106
10ª              47
11ª              35
12ª              22
-1               19
13ª              16
14ª               8
15ª               7
17ª               6
16ª               2
-2                2
20ª               1
27ª               1
22ª               1
21ª               1
18ª               1
Name: count, dtype: int64

In [97]:
df_madrid['planta'].fillna(method ='bfill', inplace= True)

/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_28976/3994935873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['planta'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_28976/3994935873.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['planta'].fillna(method ='bfill', inplace= True)

In [98]:
df_madrid['planta'].value_counts()

planta
1ª             2351
2ª             1977
3ª             1770
BAJO           1671
4ª             1416
5ª              910
6ª              643
7ª              321
ENTREPLANTA     182
SÓTANO          146
8ª              138
9ª              114
10ª              51
11ª              39
12ª              23
-1               22
13ª              18
14ª              10
15ª               7
17ª               7
16ª               2
-2                2
27ª               2
20ª               1
22ª               1
21ª               1
18ª               1
Name: count, dtype: int64

In [99]:
df_madrid['planta'].unique()

array(['5ª', '1ª', '2ª', 'BAJO', '3ª', '6ª', '4ª', '16ª', '13ª', '9ª',
       '7ª', '10ª', '8ª', '14ª', '11ª', '12ª', 'ENTREPLANTA', 'SÓTANO',
       '-1', '15ª', '17ª', '20ª', '-2', '27ª', '22ª', '21ª', '18ª'],
      dtype=object)

In [100]:
df_madrid.isnull().sum()

provincia          0
zona               0
titulo             0
precio_actual      0
metros             0
habitaciones     366
ascensor         793
planta             0
baños              0
dtype: int64

In [101]:
df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
df_madrid['ascensor'].fillna(method ='bfill', inplace= True)

/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_28976/3544064126.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_28976/3544064126.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_28976/3544064126.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['ascensor'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_28976/3544064126.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['ascensor'].fillna(method ='bfill', inplace= True)

In [102]:
df_madrid['habitaciones'].value_counts()

habitaciones
3.0     3885
2.0     3485
1.0     1686
4.0     1537
5.0      713
6.0      297
7.0      109
8.0       49
9.0       27
10.0      15
11.0      10
13.0       3
16.0       3
15.0       3
12.0       2
20.0       1
17.0       1
Name: count, dtype: int64

In [103]:
df_madrid['ascensor'].value_counts()

ascensor
S    9015
N    2811
Name: count, dtype: int64

In [104]:
df_madrid.isnull().sum()

provincia        0
zona             0
titulo           0
precio_actual    0
metros           0
habitaciones     0
ascensor         0
planta           0
baños            0
dtype: int64

In [105]:
df_madrid.duplicated(keep = 'first').sum()

np.int64(616)

In [106]:
df_madrid.duplicated().any()

np.True_

In [108]:
duplicados = df_madrid[df_madrid.duplicated(keep = False)].sort_values(by='precio_actual')

In [109]:
duplicados

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños
10147,madrid,puente-de-vallecas,"Piso en calle Sierra de Alquife, 30, San Diego...",55500,41,1.0,N,3ª,0
11128,madrid,puente-de-vallecas,"Piso en calle Sierra de Alquife, 30, San Diego...",55500,41,1.0,N,3ª,0
1359,madrid,puente-de-vallecas,"Piso en San Diego, Madrid",75000,29,1.0,N,BAJO,0
5713,madrid,puente-de-vallecas,"Piso en San Diego, Madrid",75000,29,1.0,N,BAJO,0
11347,madrid,puente-de-vallecas,"Piso en calle del Doctor Bellido, San Diego, M...",75000,30,1.0,N,BAJO,0
...,...,...,...,...,...,...,...,...,...
8191,madrid,barrio-de-salamanca,"Piso en calle de José Ortega y Gasset, Castell...",7900000,473,4.0,S,2ª,0
10019,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",8900000,455,5.0,S,5ª,0
2312,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",8900000,455,5.0,S,5ª,0
7614,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",13000000,421,5.0,S,3ª,0
9675,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",13000000,421,5.0,S,3ª,0

In [110]:
df_madrid.drop_duplicates()

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0
...,...,...,...,...,...,...,...,...,...
11821,madrid,centro,"Piso en calle del Amparo, Lavapiés-Embajadores...",189000,36,2.0,N,BAJO,0
11822,madrid,centro,"Piso en calle Gran Vía, Chueca-Justicia, Madrid",2600000,245,2.0,S,2ª,0
11823,madrid,tetuan,"Piso en calle del Capitán Blanco Argibay, Vald...",219000,56,1.0,S,BAJO,0
11824,madrid,carabanchel,"Piso en calle de Aceuchal, Vista Alegre, Madrid",165000,74,3.0,N,2ª,0
11825,madrid,san-blas,"Piso en calle de los Hermanos García Noblejas,...",178000,54,2.0,S,BAJO,0

In [112]:
df_madrid.shape

(11826, 9)